### ISSUE TITLE
please consider fdroid listing

### ISSUE THREAD

**Issue by leela52452** [wolf3d2/jbak2keyboard#2]
hello @wolf3d2 

if possible, consider listing on fdroid.
you can find more [FAQ - App Developers](https://f-droid.org/docs/FAQ_-_App_Developers/?title=FAQ_-_App_Developers) and where to [Requests For Packaging ](https://gitlab.com/fdroid/rfp)

**Comment by wolf3d2** [comment]
Спасибо, но я не хочу публиковать приложение на f-droid.


leela <notifications@github.com> 14 декабря 2019 г. 7:09:23 написал:

**Comment by leela52452** [comment]
> Спасибо, но я не хочу публиковать приложение на f-droid. 

machine translation of above: Thank you, but I don't want to publish an f-droid app.

thank u, no issues.
